/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-tidy-html5.h
 #	source generated by 4D Plugin Wizard
 #	Project : tidy-html5
 #	author : miyako
 #	2019/07/23
 #
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_TIDY_HTML5_H
#define PLUGIN_TIDY_HTML5_H

#include "4DPluginAPI.h"

#include "tidy.h"
#include "tidybuffio.h"
#include "locale.h"
#include "4DPlugin-JSON.h"
#include "C_TEXT.h"

 #if VERSIONWIN
 //#include "sprtf.h"
 #endif

void Tidy(PA_PluginParameters params);

#endif /* PLUGIN_TIDY_HTML5_H */
